service: c164_store
image: REPLACE_WITH_DOCKER_USERNAME/c164_store

servers:
  web:
    - REPLACE_WITH_EC2_PUBLIC_IP

registry:
  server: docker.io
  username: REPLACE_WITH_DOCKER_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true
    RAILS_HOST: REPLACE_WITH_EC2_PUBLIC_IP

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "c164_store_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
  context: .
  driver: docker

ssh:
  user: ubuntu
  keys:
    - REPLACE_WITH_SSH_KEY_PATH
